name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Clone and bootstrap vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install Catch2
      run: ./vcpkg/vcpkg install catch2

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/vcpkg/triplets/x64-linux.cmake

    - name: Build project
      run: cmake --build build --config Release --parallel

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure