name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure