name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@v3
        with:
          cmakeVersion: '3.10'

      - name: Configure project
        run: cmake -S . -B build
        # [CMakeLists.txt](CMakeLists.txt)

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --verbose
        # This will run tests defined in [test/unit_test.cpp](test/unit_test.cpp)
